/**
 * Aibou live approval console — real-time approvals on the watch, no IDE hook.
 *
 * Why this exists
 * ---------------
 * The Kiro IDE `preToolUse` hook (scripts/ide-approval-hook.mjs) is disabled. It
 * blocked forever on `for await (const chunk of process.stdin)`, because Kiro IDE
 * gives a hook a stdin that never reaches EOF, and the hook config set
 * `"timeout": 0` so nothing killed it. No approval was ever raised.
 *
 * This takes the opposite approach. Rather than intercepting the editor, it talks
 * to the Bridge's own ACP session, where permission requests are generated by the
 * real agent. That path is not inferred or simulated: the agent holds a JSON-RPC
 * request open, the Bridge fans it out over the WebSocket, and the tap on the
 * watch is what answers it. Deny genuinely blocks the tool.
 *
 * It stays connected and streams everything as it happens, so approvals show up
 * on the wrist the moment the agent asks.
 *
 * Usage:
 *   node scripts/watch-live.mjs [code] [--port 8787] [--cwd <dir>] [-p "prompt"]
 *
 * Then type prompts at the `aibou>` prompt. Commands:
 *   /a /d      answer the oldest pending approval from here instead of the watch
 *   /pending   list approvals still waiting
 *   /state     show session status
 *   /new       start a fresh session
 *   /quit
 */

import { createInterface } from 'node:readline';
import { readFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import WebSocket from 'ws';

const argv = process.argv.slice(2);
const flag = (name, fallback) => {
  const i = argv.indexOf(name);
  return i !== -1 && argv[i + 1] ? argv[i + 1] : fallback;
};
const PORT = flag('--port', '8787');
const CWD = flag('--cwd', process.cwd());
const FIRST_PROMPT = flag('-p', null);
const CODE = argv.find((a) => /^\d{6}$/.test(a)) ?? null;
const BASE = `http://127.0.0.1:${PORT}`;

const C = {
  dim: (s) => `\x1b[2m${s}\x1b[0m`,
  bold: (s) => `\x1b[1m${s}\x1b[0m`,
  red: (s) => `\x1b[31m${s}\x1b[0m`,
  green: (s) => `\x1b[32m${s}\x1b[0m`,
  amber: (s) => `\x1b[33m${s}\x1b[0m`,
  cyan: (s) => `\x1b[36m${s}\x1b[0m`,
};

/** Bearer token: a fresh pairing code if given, else one this machine kept. */
async function getToken() {
  if (CODE) {
    const res = await fetch(`${BASE}/api/pair`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ code: CODE }),
    });
    if (res.ok) return (await res.json()).token;
    console.log(C.amber(`  pairing code rejected (HTTP ${res.status}) — trying a stored token`));
  }
  try {
    const cfg = JSON.parse(readFileSync(join(homedir(), '.aibou', 'config.json'), 'utf-8'));
    const stored = Array.isArray(cfg.tokens)
      ? cfg.tokens.filter((t) => typeof t === 'string').at(-1)
      : null;
    if (stored) return stored;
  } catch {
    /* never paired on this machine */
  }
  return null;
}

// ─── Preflight: a clear message beats a stack trace ──────────────────────────

let health;
try {
  health = await (await fetch(`${BASE}/api/health`)).json();
} catch {
  console.error(
    C.red('\n  The Bridge is not running.\n') +
      `  Start it first, in another terminal:\n\n` +
      C.cyan('      node packages/bridge/dist/index.js\n\n') +
      `  Add ${C.cyan('--mock')} to try it without Kiro credentials.\n`,
  );
  process.exit(1);
}

const token = await getToken();
if (!token) {
  console.error(
    C.red('\n  Not paired with this Bridge.\n') +
      '  Pass the 6-digit code from the Bridge banner:\n\n' +
      C.cyan('      node scripts/watch-live.mjs <code>\n'),
  );
  process.exit(1);
}

// ─── Connection ──────────────────────────────────────────────────────────────

const frames = [];
/** Approvals still unanswered, oldest first, so /a and /d have a target. */
const pending = new Map();
let sessionId = null;
let ws;

const send = (f) => ws?.readyState === 1 && ws.send(JSON.stringify({ v: 1, ts: Date.now(), ...f }));

let rl;
/** Print without leaving the readline prompt smeared across the output. */
function say(line) {
  if (rl) rl.pause();
  process.stdout.write('\r\x1b[K' + line + '\n');
  if (rl) {
    rl.prompt(true);
    rl.resume();
  }
}

function waitFor(pred, timeout, label) {
  return new Promise((resolve, reject) => {
    const hit = frames.find(pred);
    if (hit) return resolve(hit);
    const iv = setInterval(() => {
      const f = frames.find(pred);
      if (f) {
        clearInterval(iv);
        clearTimeout(to);
        resolve(f);
      }
    }, 50);
    const to = setTimeout(() => {
      clearInterval(iv);
      reject(new Error(`timed out after ${timeout}ms waiting for ${label}`));
    }, timeout);
  });
}

/** Render the frames that matter, and keep `pending` accurate. */
function handle(f) {
  frames.push(f);

  if (f.t === 'heartbeat') return send({ t: 'pong' });

  if (f.t === 'permission.request') {
    pending.set(f.approvalId, f);
    const left = Math.max(0, Math.round((f.expiresAt - Date.now()) / 1000));
    const risk =
      f.riskTier === 'high' ? C.red('HIGH') : f.riskTier === 'medium' ? C.amber('MEDIUM') : 'low';
    say('');
    say(C.bold(C.amber('  APPROVAL PENDING — check your watch')));
    say(`    ${C.bold(f.summary)}`);
    say(C.dim(`    tool ${f.toolName}   risk ${risk}   expires in ${left}s`));
    say(C.dim(`    input ${JSON.stringify(f.toolInput)}`));
    say(C.dim(`    tap the watch, or type /a to allow or /d to deny`));
    return;
  }

  if (f.t === 'permission.resolved') {
    const req = pending.get(f.approvalId);
    pending.delete(f.approvalId);
    const how =
      f.resolution === 'user'
        ? `answered by a human${f.resolvedBy ? ` (${f.resolvedBy})` : ''}`
        : f.resolution === 'policy'
          ? `policy rule ${f.ruleId ?? '?'}`
          : 'timed out — auto-denied';
    const tag = f.decision === 'allow' ? C.green('ALLOWED') : C.red('DENIED');
    say(`  ${tag} ${C.dim(how)}${req ? ` ${C.dim('— ' + req.summary)}` : ''}`);
    return;
  }

  if (f.t === 'session.state') {
    if (f.status === 'idle') say(C.dim(`  [session ${f.status}]`));
    else {
      const src = f.statusSource === 'inferred' ? C.amber(' inferred') : '';
      say(C.dim(`  [session ${f.status}${src}${f.statusReason ? `: ${f.statusReason}` : ''}]`));
    }
    return;
  }

  if (f.t === 'event') {
    const p = f.payload ?? {};
    if (f.kind === 'agent.text' && typeof p.text === 'string') {
      // Streamed token by token; print inline so it reads like prose.
      if (rl) rl.pause();
      process.stdout.write(p.text);
      return;
    }
    if (f.kind === 'tool.start') say(C.cyan(`  > ${p.title ?? p.toolCallId ?? 'tool'}`));
    else if (f.kind === 'tool.end') {
      const text = typeof p.text === 'string' ? p.text.trim().split('\n')[0].slice(0, 100) : '';
      say(C.dim(`  < done${text ? `: ${text}` : ''}`));
    } else if (f.kind === 'usage') say(C.dim(`  [usage ${JSON.stringify(p)}]`));
    return;
  }

  if (f.t === 'error') say(C.red(`  error ${f.code}: ${f.message}`));
}

async function connect() {
  ws = new WebSocket(`ws://127.0.0.1:${PORT}/ws`);
  ws.on('message', (d) => {
    let f;
    try {
      f = JSON.parse(d.toString());
    } catch {
      return;
    }
    handle(f);
  });
  ws.on('close', () => {
    say(C.amber('  disconnected — reconnecting in 2s'));
    setTimeout(() => connect().catch(() => {}), 2000);
  });
  ws.on('error', () => {});

  await new Promise((r, j) => {
    ws.on('open', r);
    ws.on('error', j);
  });

  send({ t: 'auth', token });
  const hello = await waitFor((f) => f.t === 'hello', 10_000, 'hello');

  // Replay from 0 so a reconnect restores anything missed, including an
  // approval raised while the socket was down.
  send({ t: 'subscribe', id: 'sub', since: 0 });
  await waitFor((f) => f.t === 'ack' && f.id === 'sub', 10_000, 'subscribe ack');

  return hello;
}

const hello = await connect();
console.log(
  `\n  connected — Bridge v${hello.bridgeVersion}, mode ${
    hello.mode === 'mock' ? C.amber('MOCK (not a real Kiro session)') : C.green('LIVE')
  }`,
);

// ─── Session ─────────────────────────────────────────────────────────────────

let seq = 0;
const nextId = (p) => `${p}-${++seq}`;

async function ensureSession(forceNew = false) {
  if (!forceNew) {
    send({ t: 'session.list', id: 'list' });
    const list = await waitFor((f) => f.t === 'ack' && f.id === 'list', 10_000, 'session list');
    const reusable = (list.result ?? []).find((s) => s.status === 'idle' || s.status === 'working');
    if (reusable) {
      sessionId = reusable.id;
      console.log(`  reusing session ${C.dim(sessionId)}`);
      return;
    }
  }

  console.log(C.dim('  creating a session (a real agent takes a few seconds)...'));
  const id = nextId('create');
  send({ t: 'session.create', id, cwd: CWD });
  const made = await waitFor(
    (f) => (f.t === 'ack' || f.t === 'error') && f.id === id,
    90_000,
    'session create',
  );
  if (made.t === 'error') {
    console.error(C.red(`\n  could not create a session: ${made.code} — ${made.message}`));
    if (made.code === 'AIBOU_SESSION_LIMIT') {
      console.error('  Restart the Bridge to clear existing sessions.\n');
    }
    process.exit(1);
  }
  sessionId = made.result.id;
  console.log(`  session ${C.dim(sessionId)} in ${C.dim(CWD)}`);
}

await ensureSession();

console.log(
  `\n  ${C.bold('Type a prompt and press Enter.')} Any tool the agent wants to run\n` +
    `  raises a real approval on your watch. ${C.dim('/a allow  /d deny  /pending  /state  /new  /quit')}\n` +
    C.dim('  Try: run the shell command \'node --version\' and tell me what it prints\n'),
);

// ─── REPL ────────────────────────────────────────────────────────────────────

rl = createInterface({ input: process.stdin, output: process.stdout, prompt: 'aibou> ' });

function answerOldest(decision) {
  const oldest = [...pending.values()].sort((a, b) => a.ts - b.ts)[0];
  if (!oldest) return say(C.dim('  nothing pending'));
  send({ t: 'permission.respond', id: nextId('resp'), approvalId: oldest.approvalId, decision });
  say(C.dim(`  sent ${decision} for "${oldest.summary}" from here`));
}

rl.on('line', (raw) => {
  const line = raw.trim();
  if (line === '') return rl.prompt();

  if (line === '/quit' || line === '/q') {
    ws.removeAllListeners('close');
    ws.close();
    rl.close();
    return process.exit(0);
  }
  if (line === '/a' || line === '/allow') return answerOldest('allow'), rl.prompt();
  if (line === '/d' || line === '/deny') return answerOldest('deny'), rl.prompt();
  if (line === '/pending') {
    if (pending.size === 0) say(C.dim('  nothing pending'));
    for (const p of pending.values()) say(`  ${p.approvalId.slice(0, 8)} ${p.summary}`);
    return rl.prompt();
  }
  if (line === '/state') {
    const s = frames.filter((f) => f.t === 'session.state').pop();
    say(s ? `  ${s.status} (${s.statusSource}), ${s.pendingApprovals} pending` : C.dim('  no state yet'));
    return rl.prompt();
  }
  if (line === '/new') {
    ensureSession(true).then(() => rl.prompt());
    return;
  }
  if (line.startsWith('/')) {
    say(C.dim('  commands: /a /d /pending /state /new /quit'));
    return rl.prompt();
  }

  send({ t: 'prompt.send', id: nextId('prompt'), sessionId, text: line, source: 'text' });
  say(C.dim(`  sent`));
  rl.prompt();
});

rl.on('close', () => process.exit(0));

if (FIRST_PROMPT) {
  send({ t: 'prompt.send', id: nextId('prompt'), sessionId, text: FIRST_PROMPT, source: 'text' });
  say(C.dim(`  sent: ${FIRST_PROMPT}`));
}

rl.prompt();
